USE `xpto`;

CREATE TABLE IF NOT EXISTS `empresa` (

    ID INTEGER AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CNPJ VARCHAR( 14 ) NULL UNIQUE,
    RAZAO_SOCIAL VARCHAR( 255 ) NULL,
    NOME_FANTASIA VARCHAR( 255 ) NULL

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
