USE `xpto`;

INSERT INTO `empresa` ( CNPJ, RAZAO_SOCIAL, NOME_FANTASIA )
VALUES 
( 'CNPJ', 'RAZAO_SOCIAL', 'NOME_FANTASIA' ),
( 'CNPJ', 'RAZAO_SOCIAL', 'NOME_FANTASIA' ),
( 'CNPJ', 'RAZAO_SOCIAL', 'NOME_FANTASIA' );
